name: teaderonPlugin
version: '${project.version}'
main: com.teaderonplugin.TeaderonPlugin
api-version: 1.16

commands:
  lottery:
    description: Teaderon Lottery
    aliases:
      - teaderonlottery
  chestfreavell:
    description: Random Open Chest
    aliases:
      - chestopenfreavell
  chestromenna:
    description: Random Open Chest
    aliases:
      - chestopenromenna